### ISSUE TITLE
Weird looking stretched-out icon

### ISSUE THREAD

**Issue by tannisroot** [flathub/com.github.bcedu.valasimplehttpserver#1]
This does not look right:
![Screenshot from 2019-03-24 15-20-27](https://user-images.githubusercontent.com/10602045/54879318-85264380-4e48-11e9-8113-c91a049fb791.png)

**Comment by bcedu** [comment]
We are working in a new icon

**Comment by bcedu** [comment]
Closed by https://github.com/bcedu/ValaSimpleHTTPServer/pull/19
